### ISSUE TITLE
Junior D3 Role has too many responsibilities for a junior

### ISSUE THREAD

**Issue by LorenzoS92** [jorgef/engineeringladders#13]
I think that the description of a Junior Deveoper of D3 has too many responsibilities for a Junior profile, in the "Support" part.

In particolar, those two points sounds a little too high for a Junior profile.

`- Supports: proactively supports other team members and helps them to be successful:`
it could be confusing and written so it could be associated with a leadership figure.

`- Enforces: enforces the team processes, making sure everybody understands the benefits and tradeoffs`
This kind of thing, is lead to a more senior / leader profile.

I propose two things:

- D3 could be a Mid / Senior profile
- We could rewrote Supports and Enforces for this kind of profile.

**Comment by kerunaru** [comment]
IMHO, D3 is a Mid profile. And so D4 and D5, being the last two Senior levels.

For the Supports section, maybe it would be more related to helping others with their tasks (pair programming, chat about what should be the best way to solve a problem... This kind of situation) rather than allowing them to be successful. I think the Supports skill as it is right now should be added to the D7 at least; I expect a Senior to have some leadership skills.

**Comment by LorenzoS92** [comment]
Perfect! 
If you want, I can propose a PR with some clarifications about support things.
Ps: we can also write in the table that D3 is actually mid.

**Comment by jorgef** [comment]
These are good points, thanks for bringing them.
It is well-known that companies use "junior" and "senior" in different ways. Some orgs use mid-level for the intermediate roles while others don't.
I tried to keep the framework as generic as possible to allow companies to adapt it to their needs. 
I agree with your point that calling D3 a Junior role might be a stretch, but keep in mind than a D3 is not "mentoring" others, it is starting to show some level of maturity by supporting peers proactively and making sure that the team rules are followed by others.
I see a D3 as the last Junior level where they start showing some signs of senior behavior, it is a transitional role.
At this point I am not inclined to add a mid-level label in order to keep the framework generic, but I am open to keep discussing this in the future as I am not strongly against that either.
Having said that, if your company uses mid-level roles, you are welcome to fork the framework and adapt it to your needs, many others have done it already successfully. The chances of the framework to be 100% right for every company are pretty low, therefore its adaptation is encouraged.
Thanks again for starting the discussion, as I said, I think they are good points.

**Comment by LorenzoS92** [comment]
Ok 👍

**Comment by jorgef** [comment]
@LorenzoS92 FYI I just updated the table to remove any reference to "Junior".
The new version only says whether the role is senior or not (Senior: Yes/No).
I believe this will provide more flexibility for ppl that want to introduce a mid-level for D3 like it was your case.
I hope it helps!
