### ISSUE TITLE
TL4 has lower level than D3 in "Influence" axis

### ISSUE THREAD

**Issue by omuomugin** [jorgef/engineeringladders#23]
First of all, thanks for publishing great content.

Since I was reading it through, I found that although D3 has level of "Team" in "Influence" axis TL4 has level of "Subsystem" (which is lower than D3). 
Is this on purpose or by mistake?
For my understanding TL4 is the job level after D3 so the skill level might get higher but not lower.

Again, thanks for the wonderful content and I'm gonna share with my colleague for further discussion.

**Comment by jorgef** [comment]
Hi,

It is on purpose but, to be honest, you can make an argument either way. This is one of those areas where I always recommend adapting the ladder to your needs. What is a subsystem or a team might be different for different organizations.

Having said that, the following is the reasoning behind those levels:

As a TL4, you have a larger scope "within" your subsystem (e.g., coordinating people) but your scope at the "team" level is very limited. This is probably the first time for an individual contributor to have to balance delivering code and coordinating people. Therefore, a more focused scope (subsystem) usually helps.

Since a D3 or D4 has a narrower scope within the subsystem (they are "pure" individual contributors), they can use their technical skills to influence other subsystems too (e.g. delivering cross-cutting functionality).

According to the ladder, only a TL5 will have the experience to balance things well enough to be able to operate at a "team" level.

**Comment by omuomugin** [comment]
Thanks, that is clear.

If I'm not wrong, you are saying that this chart indicates the "scope" of the skill and there are also "depth" but that is not visible on the chart.
For another example EM5 and EM7 are both has "Manages" on "People" axis but the "depth" is likely to be different.
Is that right?

**Comment by jorgef** [comment]
**re: "depth" is not visible**

I believe the "depth" is visible in the other axes. You can clearly see how much higher are the system, people and process levels for a TL4 here:

<img width="1704" alt="Screen Shot 2022-08-16 at 5 32 50 PM" src="https://user-images.githubusercontent.com/941277/184989240-3fc3467d-5167-43c0-976e-9c1ec9135a2b.png">

Sometimes visualizing the influence axis as another dimension helps. Following your analysis, you can think of technology system, people and process as different aspects of the "depth" dimension, while influence could be part of a different "scope" dimension. You could potentially re-draw the graph using the influence axis to create some 3D volume while leaving the other 4 axes in 2D.

**re: EM5 vs EM7**

As you can see in the following picture, the main difference between EM5/6 with EM7 is that the latter influences (or manages) multiple teams. The people axis is the same because all of them "manage people", but the influence level shows that the scope is larger.

<img width="1762" alt="Screen Shot 2022-08-16 at 5 36 25 PM" src="https://user-images.githubusercontent.com/941277/184990003-870ecba3-7250-4ff8-a39a-53270fe1ea42.png">

In same cases, managing multiple teams means managing other managers (although not always). For that specific situation, I created a different section that dives deeper into assessing other managers: http://www.engineeringladders.com/Managing-Managers.html

**Comment by omuomugin** [comment]
> You could potentially re-draw the graph using the influence axis to create some 3D volume while leaving the other 4 axes in 2D.

Thanks for sharing those contexts, I finally understand the concept !
