### ISSUE TITLE
TPM / TL overlap?

### ISSUE THREAD

**Issue by Timothep** [jorgef/engineeringladders#5]
Hi @jorgef, really cool stuff, thanks!

I took it for a prototypical spin with a few employees in our Consulting Agency. Something that came regularly was an overlap between TL and TPM responsibilities. 

I love the "Tech Lead vs Engineering Manager" page. How about having one for those two as well?

**Comment by jorgef** [comment]
Hi Tim,

Thanks for the feedback. I am glad you found the framework useful.

The difference between the TPM and TL roles is evident in the technology axis. 
The TL is a technical role while the TPM is more a coordination role.
While the TL "owns" the system, the TPM or EM "owns" the delivery.
If the system is unstable or its codebase is in a bad shape, that would be responsibility of the TL.
If the team is slow, blocked or delivering poorly built features, that would be responsibility of the TPM or EM.

When would you assign that responsibility to a TPM or EM?
If the team is small and/or most features don't require coordination with other teams, usually the EM can also perform the project management tasks with no problem, no need to add a TPM role.
Otherwise, in cases where many features depend heavily on other teams' milestones, there are multiple cross-team initiatives, and visibility about progress is critical; the EM might not have enough capacity to deal with all that, and the addition of a TPM role might add a ton of value.

I hope this clarifies your question.

Jorge
